version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - php
    networks:
      - native-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - native-network

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: native
      MYSQL_USER: native
      MYSQL_PASSWORD: pass
    ports:
      - "33306:3306"
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - native-network



networks:
  native-network:
    driver: bridge
